name: Deploy to VPS via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set CI=false
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Install dependencies and build React app
        run: |
          yarn install
          npx expo export:web

      - name: FTP deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./web-build/
          server-dir: ./tinzzio/
